package Lackey::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

use FindBin;

__PACKAGE__->config(
    schema_class => 'Lackey::Schema',
    
    connect_info => {
        dsn => "dbi:SQLite:$FindBin::Bin/lib/Lackey/Model/lackey.db",
        user => '',
        password => '',
    }
);

=head1 NAME

Lackey::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Lackey>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Lackey::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.6

=head1 AUTHOR

Maxwell Cabral

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
