package Lackey::Model::hopster;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Lackey::hopster',
    
    connect_info => {
        dsn => 'dbi:SQLite:/Users/Max/Documents/_Programming/HopScotch/server/lib/Lackey/Model/hopster.db',
        user => '',
        password => '',
    }
);

=head1 NAME

Lackey::Model::hopster - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Lackey>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Lackey::hopster>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.6

=head1 AUTHOR

Maxwell Cabral

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
